messages:
   morning: ["早上好"]
   noon: ["中午好"]
   night: ["晚上好"]

webhook:
   test: "https://oapi.dingtalk.com/robot/send?access_token=936de90863c82cea7b827771864674a964f1dda7dc64436a46433eea94dade2d"

tianqi:
   url: "http://www.weather.com.cn/weather/101280601.shtml"
   days: 3
